runtime: python
env: flex
entrypoint: gunicorn -b :$PORT src.wsgi

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 5
  disk_size_gb: 10

env_variables:
  BUCKET_NAME: "post-here-classi-1612563081759.appspot.com"

handlers:
- url: /static
  static_dir: public
